Search.appendIndex(
    [
                {
            "fqsen": "\\Mursalov\\Logger\\DbWriter",
            "name": "DbWriter",
            "summary": "Class\u0020which\u0020help\u0020write\u0020log\u0020to\u0020database.",
            "url": "classes/Mursalov-Logger-DbWriter.html"
        },                {
            "fqsen": "\\Mursalov\\Logger\\DbWriter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Mursalov-Logger-DbWriter.html#method___construct"
        },                {
            "fqsen": "\\Mursalov\\Logger\\DbWriter\u003A\u003Awrite\u0028\u0029",
            "name": "write",
            "summary": "Write\u0020log\u0020into\u0020database.",
            "url": "classes/Mursalov-Logger-DbWriter.html#method_write"
        },                {
            "fqsen": "\\Mursalov\\Logger\\DbWriter\u003A\u003A\u0024formatter",
            "name": "formatter",
            "summary": "",
            "url": "classes/Mursalov-Logger-DbWriter.html#property_formatter"
        },                {
            "fqsen": "\\Mursalov\\Logger\\DbWriter\u003A\u003A\u0024dbh",
            "name": "dbh",
            "summary": "",
            "url": "classes/Mursalov-Logger-DbWriter.html#property_dbh"
        },                {
            "fqsen": "\\Mursalov\\Logger\\FileWriter",
            "name": "FileWriter",
            "summary": "Class\u0020which\u0020help\u0020write\u0020log\u0020to\u0020file",
            "url": "classes/Mursalov-Logger-FileWriter.html"
        },                {
            "fqsen": "\\Mursalov\\Logger\\FileWriter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Mursalov-Logger-FileWriter.html#method___construct"
        },                {
            "fqsen": "\\Mursalov\\Logger\\FileWriter\u003A\u003Awrite\u0028\u0029",
            "name": "write",
            "summary": "Write\u0020log\u0020into\u0020file.",
            "url": "classes/Mursalov-Logger-FileWriter.html#method_write"
        },                {
            "fqsen": "\\Mursalov\\Logger\\FileWriter\u003A\u003AsetFileName\u0028\u0029",
            "name": "setFileName",
            "summary": "",
            "url": "classes/Mursalov-Logger-FileWriter.html#method_setFileName"
        },                {
            "fqsen": "\\Mursalov\\Logger\\FileWriter\u003A\u003AsetFilePath\u0028\u0029",
            "name": "setFilePath",
            "summary": "",
            "url": "classes/Mursalov-Logger-FileWriter.html#method_setFilePath"
        },                {
            "fqsen": "\\Mursalov\\Logger\\FileWriter\u003A\u003A\u0024fileName",
            "name": "fileName",
            "summary": "",
            "url": "classes/Mursalov-Logger-FileWriter.html#property_fileName"
        },                {
            "fqsen": "\\Mursalov\\Logger\\FileWriter\u003A\u003A\u0024filePath",
            "name": "filePath",
            "summary": "",
            "url": "classes/Mursalov-Logger-FileWriter.html#property_filePath"
        },                {
            "fqsen": "\\Mursalov\\Logger\\FileWriter\u003A\u003A\u0024Formatter",
            "name": "Formatter",
            "summary": "",
            "url": "classes/Mursalov-Logger-FileWriter.html#property_Formatter"
        },                {
            "fqsen": "\\Mursalov\\Logger\\Formatter",
            "name": "Formatter",
            "summary": "Format\u0020log\u0020data.",
            "url": "classes/Mursalov-Logger-Formatter.html"
        },                {
            "fqsen": "\\Mursalov\\Logger\\Formatter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Mursalov-Logger-Formatter.html#method___construct"
        },                {
            "fqsen": "\\Mursalov\\Logger\\Formatter\u003A\u003A\u0024format",
            "name": "format",
            "summary": "",
            "url": "classes/Mursalov-Logger-Formatter.html#property_format"
        },                {
            "fqsen": "\\Mursalov\\Logger\\Formatter\u003A\u003AformatLogDate\u0028\u0029",
            "name": "formatLogDate",
            "summary": "Format\u0020log\u0020date.",
            "url": "classes/Mursalov-Logger-Formatter.html#method_formatLogDate"
        },                {
            "fqsen": "\\Mursalov\\Logger\\Formatter\u003A\u003AformatLogLevel\u0028\u0029",
            "name": "formatLogLevel",
            "summary": "Format\u0020log\u0020level.",
            "url": "classes/Mursalov-Logger-Formatter.html#method_formatLogLevel"
        },                {
            "fqsen": "\\Mursalov\\Logger\\Formatter\u003A\u003AformatLogMessage\u0028\u0029",
            "name": "formatLogMessage",
            "summary": "Format\u0020log\u0020message",
            "url": "classes/Mursalov-Logger-Formatter.html#method_formatLogMessage"
        },                {
            "fqsen": "\\Mursalov\\Logger\\Formatter\u003A\u003AformatLogContext\u0028\u0029",
            "name": "formatLogContext",
            "summary": "Format\u0020log\u0020context",
            "url": "classes/Mursalov-Logger-Formatter.html#method_formatLogContext"
        },                {
            "fqsen": "\\Mursalov\\Logger\\Formatter\u003A\u003ALOG_DATE",
            "name": "LOG_DATE",
            "summary": "",
            "url": "classes/Mursalov-Logger-Formatter.html#constant_LOG_DATE"
        },                {
            "fqsen": "\\Mursalov\\Logger\\Formatter\u003A\u003ALOG_LEVEL",
            "name": "LOG_LEVEL",
            "summary": "",
            "url": "classes/Mursalov-Logger-Formatter.html#constant_LOG_LEVEL"
        },                {
            "fqsen": "\\Mursalov\\Logger\\Formatter\u003A\u003ALOG_MESSAGE",
            "name": "LOG_MESSAGE",
            "summary": "",
            "url": "classes/Mursalov-Logger-Formatter.html#constant_LOG_MESSAGE"
        },                {
            "fqsen": "\\Mursalov\\Logger\\Formatter\u003A\u003ALOG_CONTEXT",
            "name": "LOG_CONTEXT",
            "summary": "",
            "url": "classes/Mursalov-Logger-Formatter.html#constant_LOG_CONTEXT"
        },                {
            "fqsen": "\\Mursalov\\Logger\\interfaces\\FormatterInterface",
            "name": "FormatterInterface",
            "summary": "",
            "url": "classes/Mursalov-Logger-interfaces-FormatterInterface.html"
        },                {
            "fqsen": "\\Mursalov\\Logger\\interfaces\\FormatterInterface\u003A\u003Aformat\u0028\u0029",
            "name": "format",
            "summary": "",
            "url": "classes/Mursalov-Logger-interfaces-FormatterInterface.html#method_format"
        },                {
            "fqsen": "\\Mursalov\\Logger\\interfaces\\FormatterInterface\u003A\u003AformatLogDate\u0028\u0029",
            "name": "formatLogDate",
            "summary": "",
            "url": "classes/Mursalov-Logger-interfaces-FormatterInterface.html#method_formatLogDate"
        },                {
            "fqsen": "\\Mursalov\\Logger\\interfaces\\FormatterInterface\u003A\u003AformatLogLevel\u0028\u0029",
            "name": "formatLogLevel",
            "summary": "",
            "url": "classes/Mursalov-Logger-interfaces-FormatterInterface.html#method_formatLogLevel"
        },                {
            "fqsen": "\\Mursalov\\Logger\\interfaces\\FormatterInterface\u003A\u003AformatLogMessage\u0028\u0029",
            "name": "formatLogMessage",
            "summary": "",
            "url": "classes/Mursalov-Logger-interfaces-FormatterInterface.html#method_formatLogMessage"
        },                {
            "fqsen": "\\Mursalov\\Logger\\interfaces\\FormatterInterface\u003A\u003AformatLogContext\u0028\u0029",
            "name": "formatLogContext",
            "summary": "",
            "url": "classes/Mursalov-Logger-interfaces-FormatterInterface.html#method_formatLogContext"
        },                {
            "fqsen": "\\Mursalov\\Logger\\interfaces\\WriterInterface",
            "name": "WriterInterface",
            "summary": "",
            "url": "classes/Mursalov-Logger-interfaces-WriterInterface.html"
        },                {
            "fqsen": "\\Mursalov\\Logger\\interfaces\\WriterInterface\u003A\u003Awrite\u0028\u0029",
            "name": "write",
            "summary": "",
            "url": "classes/Mursalov-Logger-interfaces-WriterInterface.html#method_write"
        },                {
            "fqsen": "\\Mursalov\\Logger\\Logger",
            "name": "Logger",
            "summary": "Logger\u0020to\u0020write\u0020log\u0020in\u0020db\u0020file\u0020and\u0020more.",
            "url": "classes/Mursalov-Logger-Logger.html"
        },                {
            "fqsen": "\\Mursalov\\Logger\\Logger\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Mursalov-Logger-Logger.html#method___construct"
        },                {
            "fqsen": "\\Mursalov\\Logger\\Logger\u003A\u003Alog\u0028\u0029",
            "name": "log",
            "summary": "Write\u0020log\u0020\u0021\u0021\u0021",
            "url": "classes/Mursalov-Logger-Logger.html#method_log"
        },                {
            "fqsen": "\\Mursalov\\Logger\\Logger\u003A\u003AsetWriter\u0028\u0029",
            "name": "setWriter",
            "summary": "Add\u0020writer\u0020to\u0020writer\u0020array.",
            "url": "classes/Mursalov-Logger-Logger.html#method_setWriter"
        },                {
            "fqsen": "\\Mursalov\\Logger\\Logger\u003A\u003A\u0024writers",
            "name": "writers",
            "summary": "Array\u0020writers\u0020which\u0020write\u0020log.",
            "url": "classes/Mursalov-Logger-Logger.html#property_writers"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Mursalov\\Logger",
            "name": "Logger",
            "summary": "",
            "url": "namespaces/mursalov-logger.html"
        },                {
            "fqsen": "\\Mursalov",
            "name": "Mursalov",
            "summary": "",
            "url": "namespaces/mursalov.html"
        },                {
            "fqsen": "\\Mursalov\\Logger\\interfaces",
            "name": "interfaces",
            "summary": "",
            "url": "namespaces/mursalov-logger-interfaces.html"
        }            ]
);
